####
GET  http://localhost:3001/razas/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Impvc2UuZnJhbmNpc2NvLmNhbXBvLmNhbXBvQGdtYWlsLmNvbSIsImlhdCI6MTYzMTY4OTc5N30.1Uo69s9ISYae5GixfYOhb2sXSRCT_dMjT9Op6XX6SZo
